/* ILIMNI Learning Intelligence Layer — canonical Big Ideas registry */
var LIL_BIG_IDEAS = [
  { id: "BIG-001", legacyId: "understanding-before-tools", title: "Start with understanding", statement: "Understanding concepts helps you master any tool.", explanation: "Concepts remain useful even when devices, apps, and menus change.", tags: ["concepts", "confidence", "transfer"], relatedMissions: [1, 5] },
  { id: "BIG-002", legacyId: "technology-serves-people", title: "People come first", statement: "Technology should adapt to people.", explanation: "Useful technology is designed and adjusted around people’s needs, contexts, and abilities.", tags: ["people", "accessibility", "purpose"], relatedMissions: [1, 5] },
  { id: "BIG-003", legacyId: "names-and-content", title: "Look beyond the name", statement: "Names identify. Understanding reveals.", explanation: "Names and extensions provide clues, but opening and understanding content tells you what something really is.", tags: ["files", "information", "critical-thinking"], relatedMissions: [6] },
  { id: "BIG-004", legacyId: "curiosity-begins-learning", title: "Stay curious", statement: "Curiosity begins discovery.", explanation: "Questions turn unfamiliar technology into something learners can investigate and understand.", tags: ["curiosity", "learning", "discovery"], relatedMissions: [5] },
  { id: "BIG-005", legacyId: "organise-to-find", title: "Organise with purpose", statement: "Organisation makes information usable.", explanation: "Clear names and sensible locations make work easier to find, share, and protect.", tags: ["files", "folders", "organisation"], relatedMissions: [2] },
  { id: "BIG-006", legacyId: "input-process-output", title: "Follow the flow", statement: "Every useful computer task transforms input into meaningful output.", explanation: "Tracing input, processing, storage, and output helps learners explain many different systems.", tags: ["input", "processing", "output"], relatedMissions: [1] }
];
